-- =============================================================================
-- ShivariVel Construction & Interiors
-- Seed Data: Service Types
-- =============================================================================
-- This seed file creates default service types for a company.
-- It should be run AFTER a company and owner profile exist.
--
-- In production, service types are created when the owner first sets up
-- their company through the Settings page.
--
-- This seed provides a reference list of the standard service types.
-- =============================================================================

-- NOTE: This seed assumes a company already exists (created via auth trigger).
-- The service_types table has DEFAULT current_company_id() on company_id,
-- so this seed must be run in an authenticated context, OR the company_id
-- must be provided explicitly.
--
-- For local Supabase development, you can:
-- 1. Create a user via the Supabase dashboard
-- 2. The auth trigger will create a company + profile
-- 3. Then run this seed with the company_id filled in
--
-- Example (replace YOUR_COMPANY_ID with actual UUID):
--
-- INSERT INTO public.service_types (company_id, name, sort_order) VALUES
--   ('YOUR_COMPANY_ID', 'Building Plan', 1),
--   ('YOUR_COMPANY_ID', '3D Plan', 2),
--   ('YOUR_COMPANY_ID', 'Approval Plan', 3),
--   ('YOUR_COMPANY_ID', 'Estimate & Valuations', 4),
--   ('YOUR_COMPANY_ID', 'Building Contractor', 5),
--   ('YOUR_COMPANY_ID', 'Site Surveying', 6),
--   ('YOUR_COMPANY_ID', '3D Elevation', 7),
--   ('YOUR_COMPANY_ID', 'False Ceiling Works', 8),
--   ('YOUR_COMPANY_ID', 'Interior & Exterior Works', 9),
--   ('YOUR_COMPANY_ID', 'Profile Light Work', 10);
